
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOHOTEL ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOROOMS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOODESCRIPTIONS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERDAYPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERDAYPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOONETIME ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOSPECIALOFFERS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOEARLYBOOKINGS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOALLOTMENTS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOCANCELLATIONS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOITEMINFOS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERIODPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERIODPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOTMPDAY ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISC ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCHOTEL ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @
--  CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCTEXT ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOHOTEL UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOHOTEL ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOROOMS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOROOMS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOODESCRIPTIONS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOODESCRIPTIONS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERDAYPRICE UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERDAYPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERDAYPRICE UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERDAYPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOONETIME UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOONETIME ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOSPECIALOFFERS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOSPECIALOFFERS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOEARLYBOOKINGS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOEARLYBOOKINGS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOALLOTMENTS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOALLOTMENTS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOCANCELLATIONS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOCANCELLATIONS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOITEMINFOS UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOITEMINFOS ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERIODPRICE UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOPERIODPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERIODPRICE UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOADDPERIODPRICE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(50.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOTMPDAY UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOTMPDAY ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISC UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISC ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCHOTEL UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCHOTEL ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCTEXT UNSET PROFILE' )  @
CALL SYSPROC.ADMIN_CMD( 'RUNSTATS ON TABLE db2inst1.TOOMISCTEXT ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL TABLESAMPLE SYSTEM(100.0) SET PROFILE' ) @

-- -----------------------------------------------------------------------------
-- EOF
-- -----------------------------------------------------------------------------
