CREATE
  OR REPLACE PROCEDURE SP_PRICING_AV_MISC (
  IN IN_TOCODE VARCHAR(5) DEFAULT ''
  ,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
  ,IN IN_DESTINATIONCODE VARCHAR(5) DEFAULT ''
  ,IN IN_PRICEDATEFROM VARCHAR(10)
  ,IN IN_PRICEDATETO VARCHAR(10)
  ,IN IN_NRADULTS INTEGER DEFAULT 2
  ,IN IN_MISCCODE VARCHAR(30) DEFAULT ''
  ,IN IN_MISCITEMCODE VARCHAR(20) DEFAULT ''
  ,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
  ,IN IN_IGNORE_XX INTEGER DEFAULT 0
  ,IN IN_IGNORE_RQ INTEGER DEFAULT 0
  ,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
  ,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
  ,IN IN_MISCKEY VARCHAR(20) DEFAULT ''
  ,IN IN_CURRENCY VARCHAR(3) DEFAULT 'CHF'
  ,IN IN_EXPORT_ONLY INTEGER DEFAULT 1
  ) DYNAMIC RESULT SETS 1

P1:

BEGIN
  DECLARE cursor1 CURSOR WITH RETURN
  FOR
  SELECT TOOMISC.TOCODE AS TOCODE
    ,TOOMISC.MISCKEY AS MISCKEY
    ,TOOMISC.DESTINATIONCODE AS DESTINATIONCODE
    ,TOOMISC.MISCCODE AS MISCCODE
    ,TOOMISC.MISCITEMCODE AS MISCITEMCODE
    ,INV.TITLE AS INVTITLE
    ,INV.DETAIL AS INVDETAIL
    ,ITIN.TITLE AS ITINTITLE
    ,ITIN.DETAIL AS ITINDETAIL
    ,TOOMISC.REGION AS REGION
    ,TOOMISC.SUBREGION AS SUBREGION
    ,TOOMISC.COUNTRY AS COUNTRY
    ,TOOMISC.COUNTRYISOCODE AS COUNTRYCODE
    ,TOOMISC.MINIMUMPERSONS AS MINIMUMPERSONS
    ,TOOMISC.MAXIMUMPERSONS AS MAXIMUMPERSONS
    ,coalesce(x.TOTAL, 0) AS TOTAL
    ,coalesce(x.STATUS, 'XX') AS STATUS
  FROM TOOMISC
  INNER JOIN TABLE (func_miscpriceav2(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NRADULTS, IN_MISCCODE, IN_MISCITEMCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_MISCKEY, IN_CURRENCY, IN_EXPORT_ONLY)) AS x ON x.MISCKEY = TOOMISC.MISCKEY
  LEFT OUTER JOIN TOOMISCTEXT AS INV ON TOOMISC.MISCKEY = INV.MISCKEY
    AND TOOMISC.TOCODE = INV.TOCODE
    AND INV.type = 'INV'
    AND INV.LANG = (
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN 'EN'
        WHEN 'FR'
          THEN 'FR'
        WHEN 'IT'
          THEN 'IT'
        ELSE 'DE'
        END
      )
  LEFT OUTER JOIN TOOMISCTEXT AS ITIN ON TOOMISC.MISCKEY = ITIN.MISCKEY
    AND TOOMISC.TOCODE = ITIN.TOCODE
    AND ITIN.type = 'ITIN'
    AND ITIN.LANG = (
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN 'EN'
        WHEN 'FR'
          THEN 'FR'
        WHEN 'IT'
          THEN 'IT'
        ELSE 'DE'
        END
      )
  WHERE x.MISCKEY = TOOMISC.MISCKEY;

  -- Cursor left open for client application
  OPEN cursor1;
END P1
@



CREATE
  OR REPLACE PROCEDURE SP_PRICING_AV_MISC_TBL (
  IN IN_TOCODE VARCHAR(5) DEFAULT ''
  ,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
  ,IN IN_DESTINATIONCODE VARCHAR(5) DEFAULT ''
  ,IN IN_PRICEDATEFROM VARCHAR(10)
  ,IN IN_PRICEDATETO VARCHAR(10)
  ,IN IN_NRADULTS INTEGER DEFAULT 2
  ,IN IN_MISCCODE VARCHAR(30) DEFAULT ''
  ,IN IN_MISCITEMCODE VARCHAR(20) DEFAULT ''
  ,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
  ,IN IN_IGNORE_XX INTEGER DEFAULT 0
  ,IN IN_IGNORE_RQ INTEGER DEFAULT 0
  ,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
  ,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
  ,IN IN_MISCKEY VARCHAR(20) DEFAULT ''
  ,IN IN_CURRENCY VARCHAR(3) DEFAULT 'CHF'
  ,IN IN_EXPORT_ONLY INTEGER DEFAULT 1
  ) DYNAMIC RESULT SETS 1

P1:

BEGIN
  DECLARE cursor1 CURSOR WITH RETURN
  FOR
  SELECT TOOMISC.TOCODE AS TOCODE
    ,TOOMISC.MISCKEY AS MISCKEY
    ,TOOMISC.DESTINATIONCODE AS DESTINATIONCODE
    ,TOOMISC.MISCCODE AS MISCCODE
    ,TOOMISC.MISCITEMCODE AS MISCITEMCODE
    ,NR AS NR
    ,PRICE AS PRICE
    ,TOTAL AS TOTAL
    ,TYPE1 AS TYPE1
    ,TYPE2 AS TYPE2
    ,FROMDATE AS FROMDATE
    ,TODATE AS TODATE
    ,x.DESCID AS DESCID
    ,P_SEQ AS P_SEQ
    ,STATUS AS STATUS
    ,TOODESCRIPTIONS.ID
    ,(
      CASE IN_LANGCODE
        WHEN 'EN'
          THEN DESCEN
        WHEN 'FR'
          THEN DESCFR
        WHEN 'IT'
          THEN DESCIT
        ELSE DESCDE
        END
      ) AS PRICEDESC
    ,PRICETYPE AS PRICETYPE
  FROM TOOMISC
  INNER JOIN TABLE (func_miscpriceav2_tbl(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NRADULTS, IN_MISCCODE, IN_MISCITEMCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_MISCKEY, IN_CURRENCY, IN_EXPORT_ONLY)) AS x ON x.TOCODE = TOOMISC.TOCODE
    AND x.MISCKEY = TOOMISC.MISCKEY
  LEFT OUTER JOIN TOODESCRIPTIONS ON TOODESCRIPTIONS.ITEMKEY = x.MISCKEY
    AND TOODESCRIPTIONS.ITEMTYPE = 'M'
    AND TOODESCRIPTIONS.TOCODE = IN_TOCODE
    AND TOODESCRIPTIONS.DESCID = x.DESCID
  WHERE TOOMISC.TOCODE = IN_TOCODE
    AND TOOMISC.MISCKEY = x.MISCKEY
  ORDER BY x.TOCODE
    ,x.MISCKEY
    ,(
      CASE x.TYPE1
        WHEN 'PP'
          THEN 1
        WHEN 'APP'
          THEN 2
        WHEN 'PDP'
          THEN 3
        WHEN 'APDP'
          THEN 4
        WHEN 'OT'
          THEN 5
        WHEN 'SO'
          THEN 6
        WHEN 'EB'
          THEN 7
        WHEN 'EBPCT0'
          THEN 8
        ELSE 9
        END
      ) ASC
    ,x.TYPE2 ASC
    ,x.FROMDATE ASC;

  -- Cursor left open for client application
  OPEN cursor1;
END P1
@
