CREATE
  OR REPLACE PROCEDURE SP_PRICING_AV_HOTEL (
  IN IN_TOCODE VARCHAR(5) DEFAULT ''
  ,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
  ,IN IN_DESTINATIONCODE VARCHAR(5) DEFAULT ''
  ,IN IN_PRICEDATEFROM VARCHAR(10)
  ,IN IN_PRICEDATETO VARCHAR(10)
  ,IN IN_NORMALOCCUPANCY INTEGER DEFAULT 2
  ,IN IN_HOTELCODE VARCHAR(30) DEFAULT ''
  ,IN IN_ROOMCODE VARCHAR(20) DEFAULT ''
  ,IN IN_TOURBOMEALCODE VARCHAR(5) DEFAULT ''
  ,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
  ,IN IN_IGNORE_XX INTEGER DEFAULT 0
  ,IN IN_IGNORE_RQ INTEGER DEFAULT 0
  ,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
  ,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
  ,IN IN_ROOMKEY VARCHAR(20) DEFAULT ''
  ,IN IN_HOTELKEY VARCHAR(20) DEFAULT ''
  ) DYNAMIC RESULT SETS 1

P1:

BEGIN
  DECLARE cursor1 CURSOR WITH RETURN
  FOR
  SELECT r.TOCODE AS TOCODE
    ,r.ROOMKEY AS ROOMKEY
    ,h.HOTELKEY AS HOTELKEY
    ,h.DESTINATIONCODE AS DESTINATIONCODE
    ,h.HOTELCODE AS HOTELCODE
    ,r.TOURBOCODE AS ROOMCODE
    ,r.TOURBOMEALCODE AS MEALCODE
    ,h.CATEGORY AS CATEGORY
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN h.HOTELNAMEEN
        WHEN 'FR'
          THEN h.HOTELNAMEFR
        WHEN 'IT'
          THEN h.HOTELNAMEIT
        ELSE h.HOTELNAMEDE
        END
      ) AS HOTELNAME
    ,h.ADDRESS1 AS ADDRESS1
    ,h.ADDRESS2 AS ADDRESS2
    ,h.CITY asCITY
    ,h.COUNTRY AS COUNTRY
    ,h.COUNTRYISOCODE AS COUNTRYCODE
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.ROOMTYPEEN
        WHEN 'FR'
          THEN r.ROOMTYPEFR
        WHEN 'IT'
          THEN r.ROOMTYPEIT
        ELSE r.ROOMTYPEDE
        END
      ) AS ROOMTYPE
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.DESCRIPTIONEN
        WHEN 'FR'
          THEN r.DESCRIPTIONFR
        WHEN 'IT'
          THEN r.DESCRIPTIONIT
        ELSE r.DESCRIPTIONDE
        END
      ) AS DESCRIPTION
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.MEALDESCRIPTIONEN
        WHEN 'FR'
          THEN r.MEALDESCRIPTIONFR
        WHEN 'IT'
          THEN r.MEALDESCRIPTIONIT
        ELSE r.MEALDESCRIPTIONDE
        END
      ) AS MEALDESCRIPTION
    ,r.MAXADULTS AS MAXADULTS
    ,r.EXTRABEDCHILDREN AS EXTRABEDCHILDREN
    ,r.NORMALOCCUPANCY AS NORMALOCCUPANCY
    ,r.MINIMALOCCUPANCY AS MINIMALOCCUPANCY
    ,r.MAXIMALOCCUPANCY AS MAXIMALOCCUPANCY
    ,h.GIATAID AS GIATAID
    ,coalesce(TOTAL, 0) AS TOTAL
    ,coalesce(STATUS, 'XX') AS STATUS
  FROM TOOHOTEL h
  INNER JOIN TOOROOMS r ON h.HOTELKEY = r.HOTELKEY
  INNER JOIN TABLE (func_hotelpriceav(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NORMALOCCUPANCY, IN_HOTELCODE, IN_ROOMCODE, IN_TOURBOMEALCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_ROOMKEY, IN_HOTELKEY)) AS x ON x.TOCODE = r.TOCODE
    AND x.ROOMKEY = r.ROOMKEY
  ORDER BY h.DESTINATIONCODE
    ,h.HOTELCODE
    ,r.HOTELKEY;

  -- Cursor left open for client application
  OPEN cursor1;
END P1
@



CREATE
  OR REPLACE PROCEDURE SP_PRICING_AV_HOTEL_TBL (
  IN IN_TOCODE VARCHAR(5) DEFAULT ''
  ,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
  ,IN IN_DESTINATIONCODE VARCHAR(5) DEFAULT ''
  ,IN IN_PRICEDATEFROM VARCHAR(10)
  ,IN IN_PRICEDATETO VARCHAR(10)
  ,IN IN_NORMALOCCUPANCY INTEGER DEFAULT 2
  ,IN IN_HOTELCODE VARCHAR(30) DEFAULT ''
  ,IN IN_ROOMCODE VARCHAR(20) DEFAULT ''
  ,IN IN_TOURBOMEALCODE VARCHAR(5) DEFAULT ''
  ,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
  ,IN IN_IGNORE_XX INTEGER DEFAULT 0
  ,IN IN_IGNORE_RQ INTEGER DEFAULT 0
  ,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
  ,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
  ,IN IN_ROOMKEY VARCHAR(20) DEFAULT ''
  ,IN IN_HOTELKEY VARCHAR(20) DEFAULT ''
  ) DYNAMIC RESULT SETS 1

P1:

BEGIN
  DECLARE cursor1 CURSOR WITH RETURN
  FOR
  SELECT r.TOCODE AS TOCODE
    ,r.ROOMKEY AS ROOMKEY
    ,h.DESTINATIONCODE AS DESTINATIONCODE
    ,h.HOTELCODE AS HOTELCODE
    ,r.TOURBOCODE AS ROOMCODE
    ,r.TOURBOMEALCODE AS MEALCODE
    ,h.CATEGORY AS CATEGORY
    ,x.NR AS NR
    ,x.PRICE AS PRICE
    ,x.TOTAL AS TOTAL
    ,x.TYPE1 AS TYPE1
    ,x.TYPE2 AS TYPE2
    ,x.FROMDATE AS FROMDATE
    ,x.TODATE AS TODATE
    ,x.DESCID AS DESCID
    ,x.P_SEQ AS P_SEQ
    ,(
      CASE IN_LANGCODE
        WHEN 'EN'
          THEN DESCEN
        WHEN 'FR'
          THEN DESCFR
        WHEN 'IT'
          THEN DESCIT
        ELSE DESCDE
        END
      ) AS PRICEDESC
    ,coalesce(x.STATUS, 'XX') AS STATUS
    ,x.PRICETYPE AS PRICETYPE
  FROM TABLE (func_hotelpriceav_tbl(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NORMALOCCUPANCY, IN_HOTELCODE, IN_ROOMCODE, IN_TOURBOMEALCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_ROOMKEY, IN_HOTELKEY)) AS x
  INNER JOIN TOOROOMs r ON r.ROOMKEY = x.ROOMKEY
  INNER JOIN TOOHOTEL h ON h.HOTELKEY = r.HOTELKEY
  LEFT OUTER JOIN TOODESCRIPTIONS ON TOODESCRIPTIONS.ITEMKEY = x.ROOMKEY
    AND TOODESCRIPTIONS.ITEMTYPE = 'H'
    AND TOODESCRIPTIONS.TOCODE = ''
    AND TOODESCRIPTIONS.DESCID = x.DESCID
  WHERE r.TOCODE = IN_TOCODE
    AND h.TOCODE = IN_TOCODE
    AND r.ROOMKEY = x.ROOMKEY
    AND h.HOTELKEY = r.HOTELKEY
    AND x.ROOMKEY = r.ROOMKEY
  ORDER BY x.TOCODE
    ,x.ROOMKEY
    ,(
      CASE x.TYPE1
        WHEN 'PP'
          THEN 1
        WHEN 'APP'
          THEN 2
        WHEN 'PDP'
          THEN 3
        WHEN 'APDP'
          THEN 4
        WHEN 'OT'
          THEN 5
        WHEN 'SO'
          THEN 6
        WHEN 'EB'
          THEN 7
        WHEN 'EBPCT0'
          THEN 8
        ELSE 9
        END
      ) ASC
    ,x.TYPE2 ASC
    ,x.FROMDATE ASC;

  -- Cursor left open for client application
  OPEN cursor1;
END P1
@

