CREATE
  OR REPLACE PROCEDURE SP_PRICING_AV_HOTEL (
  IN IN_TOCODE VARCHAR(5) DEFAULT ''
  ,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
  ,IN IN_DESTINATIONCODE VARCHAR(5) DEFAULT ''
  ,IN IN_PRICEDATEFROM VARCHAR(10)
  ,IN IN_PRICEDATETO VARCHAR(10)
  ,IN IN_NORMALOCCUPANCY INTEGER DEFAULT 2
  ,IN IN_HOTELCODE VARCHAR(30) DEFAULT ''
  ,IN IN_ROOMCODE VARCHAR(20) DEFAULT ''
  ,IN IN_TOURBOMEALCODE VARCHAR(5) DEFAULT ''
  ,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
  ,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
  ,IN IN_IGNORE_XX INTEGER DEFAULT 0
  ,IN IN_IGNORE_RQ INTEGER DEFAULT 0
  ,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
  ,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
  ,IN IN_ROOMKEY VARCHAR(20) DEFAULT ''
  ,IN IN_HOTELKEY VARCHAR(20) DEFAULT ''
  ) DYNAMIC RESULT SETS 1

P1:

BEGIN
  DECLARE cursor1 CURSOR WITH RETURN
  FOR
  SELECT r.ROOMKEY AS ROOMKEY
    ,h.HOTELKEY AS HOTELKEY
    ,h.DESTINATIONCODE AS DESTINATIONCODE
    ,h.HOTELCODE AS HOTELCODE
    ,r.TOURBOCODE AS ROOMCODE
    ,r.TOURBOMEALCODE AS MEALCODE
    ,h.CATEGORY AS CATEGORY
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN h.HOTELNAMEEN
        WHEN 'FR'
          THEN h.HOTELNAMEFR
        WHEN 'IT'
          THEN h.HOTELNAMEIT
        ELSE h.HOTELNAMEDE
        END
      ) AS HOTELNAME
    ,h.ADDRESS1 AS ADDRESS1
    ,h.ADDRESS2 AS ADDRESS2
    ,h.CITY asCITY
    ,h.COUNTRY AS COUNTRY
    ,h.COUNTRYISOCODE AS COUNTRYCODE
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.ROOMTYPEEN
        WHEN 'FR'
          THEN r.ROOMTYPEFR
        WHEN 'IT'
          THEN r.ROOMTYPEIT
        ELSE r.ROOMTYPEDE
        END
      ) AS ROOMTYPE
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.DESCRIPTIONEN
        WHEN 'FR'
          THEN r.DESCRIPTIONFR
        WHEN 'IT'
          THEN r.DESCRIPTIONIT
        ELSE r.DESCRIPTIONDE
        END
      ) AS DESCRIPTION
    ,(
      CASE upper(IN_LANGCODE)
        WHEN 'EN'
          THEN r.MEALDESCRIPTIONEN
        WHEN 'FR'
          THEN r.MEALDESCRIPTIONFR
        WHEN 'IT'
          THEN r.MEALDESCRIPTIONIT
        ELSE r.MEALDESCRIPTIONDE
        END
      ) AS MEALDESCRIPTION
    ,r.MAXADULTS AS MAXADULTS
    ,r.EXTRABEDCHILDREN AS EXTRABEDCHILDREN
    ,r.NORMALOCCUPANCY AS NORMALOCCUPANCY
    ,r.MINIMALOCCUPANCY AS MINIMALOCCUPANCY
    ,r.MAXIMALOCCUPANCY AS MAXIMALOCCUPANCY
    ,h.GIATAID AS GIATAID
    ,coalesce(TOTAL, 0) AS TOTAL
    ,coalesce(STATUS, 'XX') AS STATUS
  FROM TOOHOTEL h
  INNER JOIN TOOROOMS r ON h.HOTELKEY = r.HOTELKEY
  INNER JOIN TABLE (func_hotelpriceav(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NORMALOCCUPANCY, IN_HOTELCODE, IN_ROOMCODE, IN_TOURBOMEALCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_ROOMKEY, IN_HOTELKEY)) AS x ON x.TOCODE = r.TOCODE
    AND x.ROOMKEY = r.ROOMKEY
  ORDER BY h.DESTINATIONCODE
    ,h.HOTELCODE
    ,r.HOTELKEY;

  -- Cursor left open for client application
  OPEN cursor1;
END

P1
