CREATE
	OR REPLACE PROCEDURE SP_PRICING_AV_MISC (
	IN IN_TOCODE VARCHAR(5)
	,IN IN_LANGCODE VARCHAR(2) DEFAULT 'DE'
	,IN IN_DESTINATIONCODE VARCHAR(5)
	,IN IN_PRICEDATEFROM VARCHAR(10)
	,IN IN_PRICEDATETO VARCHAR(10)
	,IN IN_NRADULTS INTEGER DEFAULT 2
	,IN IN_MISCCODE VARCHAR(30) DEFAULT ''
	,IN IN_MISCITEMCODE VARCHAR(20) DEFAULT ''
	,IN IN_CHDDOB1 VARCHAR(10) DEFAULT ''
	,IN IN_CHDDOB2 VARCHAR(10) DEFAULT ''
	,IN IN_CHDDOB3 VARCHAR(10) DEFAULT ''
	,IN IN_CHDDOB4 VARCHAR(10) DEFAULT ''
	,IN IN_IGNORE_XX INTEGER DEFAULT 0
	,IN IN_IGNORE_RQ INTEGER DEFAULT 0
	,IN IN_IGNORE_PRICE0 INTEGER DEFAULT 1
	,IN IN_CURRENTDATE VARCHAR(10) DEFAULT ''
	,IN IN_MISCKEY VARCHAR(20) DEFAULT ''
	) DYNAMIC RESULT SETS 1

P1: BEGIN

  DECLARE pricedatefrom DATE;
  DECLARE pricedateto DATE;
  DECLARE cdob1 DATE;
  DECLARE cdob2 DATE;
  DECLARE cdob3 DATE;
  DECLARE cdob4 DATE;
  DECLARE currentdate DATE;

  SET pricedatefrom = cast(nullif(IN_PRICEDATEFROM,'') as date) ;
  SET pricedateto = cast(nullif(IN_PRICEDATETO,'') as date) ;
  SET cdob1 = cast(nullif(IN_CHDDOB1,'') as date) ;
  SET cdob2 = cast(nullif(IN_CHDDOB2,'') as date) ;
  SET cdob3 = cast(nullif(IN_CHDDOB3,'') as date) ;
  SET cdob4 = cast(nullif(IN_CHDDOB4,'') as date) ;
  SET currentdate = coalesce(cast(nullif(IN_CURRENTDATE,'') as date), CURRENT DATE) ;

P2: BEGIN
	DECLARE cursor1 CURSOR WITH RETURN
	FOR
	
SELECT TOOMISC.MISCKEY AS MISCKEY
	,INV.TITLE AS INVTITLE
	,INV.DETAIL AS INVDETAIL
	,ITIN.TITLE AS ITINTITLE
	,ITIN.DETAIL AS ITINDETAIL
	,TOOMISC.REGION AS REGION
	,TOOMISC.SUBREGION AS SUBREGION
	,TOOMISC.COUNTRY AS COUNTRY
	,TOOMISC.COUNTRYISOCODE AS COUNTRYCODE
	,TOOMISC.DESTINATIONCODE AS DESTINATIONCODE
	,TOOMISC.MISCCODE AS MISCCODE
	,TOOMISC.MISCITEMCODE AS MISCITEMCODE
	,TOOMISC.MINIMUMPERSONS AS MINIMUMPERSONS
	,TOOMISC.MAXIMUMPERSONS AS MAXIMUMPERSONS
	,coalesce(x.TOTAL, 0) AS TOTAL
	,coalesce(x.STATUS, 'XX') AS STATUS
FROM TOOMISC
INNER JOIN TABLE (func_miscpriceav2(IN_TOCODE, IN_DESTINATIONCODE, IN_PRICEDATEFROM, IN_PRICEDATETO, IN_NRADULTS, IN_MISCCODE, IN_MISCITEMCODE, IN_CHDDOB1, IN_CHDDOB2, IN_CHDDOB3, IN_CHDDOB4, IN_IGNORE_XX, IN_IGNORE_RQ, IN_IGNORE_PRICE0, IN_CURRENTDATE, IN_MISCKEY)) AS x ON x.MISCKEY = TOOMISC.MISCKEY
LEFT OUTER JOIN TOOMISCTEXT AS INV ON TOOMISC.MISCKEY = INV.MISCKEY
	AND TOOMISC.TOCODE = INV.TOCODE
	AND INV.type = 'INV'
	AND INV.LANG = (
		CASE upper(IN_LANGCODE)
			WHEN 'EN'
				THEN 'EN'
			WHEN 'FR'
				THEN 'FR'
			WHEN 'IT'
				THEN 'IT'
			ELSE 'DE'
			END
		)
LEFT OUTER JOIN TOOMISCTEXT AS ITIN ON TOOMISC.MISCKEY = ITIN.MISCKEY
	AND TOOMISC.TOCODE = ITIN.TOCODE
	AND ITIN.type = 'ITIN'
	AND ITIN.LANG = (
		CASE upper(IN_LANGCODE)
			WHEN 'EN'
				THEN 'EN'
			WHEN 'FR'
				THEN 'FR'
			WHEN 'IT'
				THEN 'IT'
			ELSE 'DE'
			END
		)
WHERE x.MISCKEY = TOOMISC.MISCKEY;

	-- Cursor left open for client application
	OPEN cursor1;	
END P2;
END P1